import Config

# Configure your database
config :pdf_tips_elixir, PdfTipsElixir.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "pdf_tips_elixir_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10,
  types: PdfTipsElixir.PostgresTypes

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :pdf_tips_elixir, PdfTipsElixirWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "NtU2xeQzYuVxOsC26SHLGwoQOsMkc3PuiRskuG7OkrB2uXSrAgyw2XU6nxr2dwuz",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:pdf_tips_elixir, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:pdf_tips_elixir, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :pdf_tips_elixir, PdfTipsElixirWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/pdf_tips_elixir_web/router\.ex$"E,
      ~r"lib/pdf_tips_elixir_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :pdf_tips_elixir, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Configure Azure AD for development (use env vars or test values)
config :ueberauth, Ueberauth.Strategy.AzureAD.OAuth,
  client_id: System.get_env("AZURE_CLIENT_ID") || "dev-client-id",
  client_secret: System.get_env("AZURE_CLIENT_SECRET") || "dev-client-secret",
  tenant_id: System.get_env("AZURE_TENANT_ID") || "dev-tenant-id"

# Cloak key for development (32 bytes, base64 encoded)
# Generate with: :crypto.strong_rand_bytes(32) |> Base.encode64()
config :pdf_tips_elixir, PdfTipsElixir.Vault,
  ciphers: [
    default: {
      Cloak.Ciphers.AES.GCM,
      tag: "AES.GCM.V1",
      key: Base.decode64!("O6f8FKDZyXNp5sGz+u0U1L3bvN2mHfQ8R9tJkYWxMnw=")
    }
  ]
